name: Deploy Text Operator App

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t mytextoperator .

      - name: Login to DockerHub
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASS }}

      - name: Push Docker image
        run: |
          docker tag mytextoperator ${{ secrets.DOCKER_USER }}/mytextoperator
          docker push ${{ secrets.DOCKER_USER }}/mytextoperator:latest


